# Generated by Django 5.2.1 on 2025-06-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscribed_publishers',
            field=models.ManyToManyField(blank=True, help_text='Publishers that the user (as a reader) is subscribed to.', related_name='subscribers', to='newsapp.publisher'),
        ),
    ]
