# Generated by Django 5.2.1 on 2025-06-03 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_alter_customuser_subscribed_publishers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
