# Generated by Django 5.2.1 on 2025-06-03 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_alter_newsletter_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.publisher'),
        ),
    ]
