# Generated by Django 5.2.1 on 2025-06-15 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_alter_customuser_subscribed_publishers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='newsapp.publisher'),
        ),
    ]
