# Generated by Django 5.2.1 on 2025-06-19 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_alter_newsletter_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(help_text='User who wrote the article (typically a journalist).', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(help_text='Publisher the article belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='newsapp.publisher'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscribed_publishers',
            field=models.ManyToManyField(blank=True, help_text='Publishers that the user (as a reader) is subscribed to.', related_name='subscribers', to='newsapp.publisher'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='author',
            field=models.ForeignKey(help_text='User who authored the newsletter.', on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='publisher',
            field=models.ForeignKey(help_text='Publisher the newsletter is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='newsapp.publisher'),
        ),
    ]
