# Generated by Django 5.2.1 on 2025-06-19 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_alter_article_author_alter_article_publisher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='user',
            field=models.OneToOneField(blank=True, help_text='The journalist user associated with this publisher.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
